version: '3'

services:
  pgsql:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsql'
    restart: always
    env_file:
      - ./.env
    # environment:
    #   POSTGRES_USER: pguser
    #   POSTGRES_PASSWORD: pgpassword
    # volumes:
    #   - pg-data:/var/lib/postgresql/data
# volumes:
#   pg-data:
