version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    # environment:
    #   POSTGRES_USER: pguser
    #   POSTGRES_PASSWORD: pgpassword
    # volumes:
    #   - pg-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  api:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    depends_on:
      - db
    command: ['yarn', 'start:dev']
# volumes:
#   pg-data:
